apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinite-calls
  labels:
    app: infinite-calls
spec:
  replicas: 0
  selector:
    matchLabels:
      app: infinite-calls
  template:  # Corrected indentation
    metadata:
      labels:
        app: infinite-calls
    spec:
      containers:
      - name: infinite-calls
        image: busybox
        command:
        - /bin/sh
        - -c
        - "while true; do wget -q -O- http://demo-app-service.default.svc.cluster.local; done"
