# Default values for demo-helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
name: demo-app

image:
  repository: mosesonwuzua/holyghost
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.1.0"
  port: 3000

imagePullSecrets:
  name: docker-secret  

service:
  type: ClusterIP
  port: 80

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 40m
      memory: 40Mi

